[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
stablecoin = "8AtmcsEj1wKLT2g6erpbvVyCMrvHeVdw8eTrUsa2Mtr4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
